/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ia;

import com.theokanning.openai.service.OpenAiService;
import com.theokanning.openai.completion.CompletionRequest;

public class App {

    public static void main(String[] args) {
        String openAIKey;
        if(args.length>0 && args[0]!=null && args[0].startsWith("sk")) {
            openAIKey = args[0];
        }
        else {
            System.out.println("No API Key");
            return;
        }
        OpenAiService service = new OpenAiService(openAIKey);
CompletionRequest completionRequest = CompletionRequest.builder()
        .prompt("Somebody once told me the world is gonna roll me")
        .model("ada")
        .echo(true)
        .build();
service.createCompletion(completionRequest).getChoices().forEach(System.out::println);
        //System.out.println(new App().getGreeting());
    }
}
