/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ia;

import com.theokanning.openai.service.OpenAiService;
import com.theokanning.openai.completion.CompletionRequest;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        OpenAiService service = new OpenAiService("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");
CompletionRequest completionRequest = CompletionRequest.builder()
        .prompt("Somebody once told me the world is gonna roll me")
        .model("ada")
        .echo(true)
        .build();
service.createCompletion(completionRequest).getChoices().forEach(System.out::println);
        //System.out.println(new App().getGreeting());
    }
}
